;---------------T---------T---------------------T----------\x10
; Path: D:\Amiga\KrustWB3\Output\Dev\github\rust-amiga-emul-ami-test-runner\tests\test_suite.s
; This file is autogenerated

	; rts in case this source is run by mistake
	rts

test_suite
	dc.l	addi_byte_immediate_data_to_data_register_direct
	dc.l	addi_byte_immediate_data_to_absolute_short
	dc.l	this_test_is_for_testing_purposes_only
	dc.l	lsl_b_register_by_immediate
	dc.l	lsl_register_by_immediate_byte_negative
	dc.l	lsl_register_by_immediate_byte_zero
	dc.l	lsl_register_by_immediate_byte_extend_carry
	dc.l	lsl_register_by_immediate_word

	dc.l	$0

	include	"addi.s"
	include	"lslr.s"
